{% set name = "loghub" %}
{% set version = "0.3.1" %}
{% set hash_type = "sha256" %}
{% set hash = "1b6f9a11552887db980acf0c4117ffd333e3165003968b3767d7981210a29357" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - loghub = loghub.cli.main:main
    - loghub-labels = loghub.cli.label_creator:main

requirements:
  build:
    - python
    - setuptools
  run:
    - jinja2
    - python

test:
  commands:
    - loghub --help
    - loghub-labels --help

about:
  home: https://github.com/spyder-ide/loghub
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Generate changelogs based on Github milestones or tags.
  description: |
    Generate changelogs based on Github milestones or tags.
  dev_url: https://github.com/spyder-ide/loghub

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
