# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hmpHdGO+EB3S7QH/hvoP8tr6MlhgWi57ihwv60mv97LlX3seJMLvlKZkoVqh8xVdtZ/mfBckMQPfbQidPUGVUSPkW01psTZVciWrmWzAii5omOiMx/WmwURhUOd0lJAc2bZejfUGljHfwJY+Natk0RzBjJtckUpUredB1XttgLxarbijFHBNNKyGmUyMADBPlqPuKKJi+/X/9KnYAmJXgdRXM4OntfNr2GooSdOlwU3Vtjy2UXiYaBepagb7B5MRMbOngmn0A1yS6wjl7sPtImvQ7Ifd/XqHQuNKrjdeVd8HtYTWg9NSrwpUPBtyndHTf2MHOmaMPVj8ioYUrW/KMAaJkOkQgpbKe/FbQ+FJvhPT0nx9qehoqgAXe8hJqT/lIy0y+dmFumU9/xrunypA4wjnT21j2zepfoXkpzJWiWiL1BXOPfvRE+nDBDyWiAMVvDwuk1Jopz6Z+//gVVnNpApbcRgVqTX6Kgt5uCZPqYtLAZw7Jvg5lc88rhr2Goif9iAmvTvP5eV9OJ275DJkQBalP/5BCgVrZME/aLROQv7jJ6yGTCaABlUNV22qapOM1p1NwPiinptur7co7gDw3qADhm2oMOYpJjy58FDKAi6UA4Hl8YfWMHB0mLo5IdkdpFBViyQ3tDgnjpZxvIhnUUkRrdb0F6Sv5wJ9UsFAysU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
