travis:
  secure:
    BINSTAR_TOKEN: SbKTN2VD4sS6pNf+zG2VxubN3HLZUrIKDqVwBMDoF/l0yGql9PFIN/KL00QtyIRQS2G+2+tEFus1Mgqq468o+O8r4TD2/Be0LZ5KxKRlyOa1ZS7xqNrLEgkT2akR0SmWRkafrxg+Vlb9P1p5JetaweQSGQbS6+iW59FCEd9qfqw9TAzgXp9bq4n1HczHDfKFYEp3Z8msC6rc0BAQ+pZPZZxDHKdG3XfkRPGK614rw0QykEFGFOBZcB21HbtpB2N9ivvBjfX0B4XbjP5nycIys8QvioXP4LabGs3vwZOdR7bIniuJpNgJYgIXbwIatMkG0gNFeDN7zJcqlW16CIIax3JZBJotXL0VBOYJlGlQehwmQDzEat6XPZsH64jYGqBVpq63q4pF6/BNqzA1Z3E11rd3EngGsm+yrGHDONnYN4OrjvfgQdq66oikeZLBUCC9ScgQCwRfj44vKuiJll6mmSAR/izzvtUPsKEm1BujY2mgC7B6HkTxQh6oS69ivba99JmapIozq/9I2h7d3h+5m51/Wd+V7Ro8V7PLG5NEnd/YUpOuq6XVKhUUxCYWHH/kI9tREAKtoGOQk7Q9xntOK9tGXOJCqVjydDh69W8HzgC/cmOptUzHPR2yBT8O02SYJyg/L7gJ84Cvhe7TxgABv5DI8FpzNmAuG0fue5/5fEs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
