travis:
  secure:
    BINSTAR_TOKEN: Loa+vIJAtW7WIZF8duJe71id+w8N9oO/nfId1w4hcUf6lBgWD96k5EzOruoYLWmaYpGqwBJ616WHT688OT9CG3rnYP9nPm4RtZVMg9yJUriWG860YJU4G2lW7Iw6QxVPwyRhsO1SyhAhR7r2gx7op/yFHnqXEt0hCT+gjJxsn3zgRjUA/BDQfjKZezfxVHAHoT67yVZE9Mx5oTp4aon4yDnR+rbf5uryFOj6fRKdrOAiO/S7rqUB7irf+O2VNk+vt46zInXCAxtW2BjrfgAdZAOw7wARjo27i5T1kYFTFiY5PAal8/exi3VEtigxnzdkiet130flwIn9NOzwlr7oHE9fSgC8wDuZ2vxLvkaiElDZAMYFrg5KjvfgbpXARGpXVu9A+3v7FXhYGCoFHyReSFWitApdX08o5foJk+cAI9NTOdFrRqztzBpAwXJw+3m1Pu5+FmYVQ1SN5x1468WSitzJmgVqGa6zV+PD70oTC61uJvdYYRAuQFW3Rfe4HE/VH2+3ATeMQXhSRf+ycIR6eRWwqQpZgmJ8e+SHcOProshnGaceWqD2nUEX/P0eQemgaiLA8xwG4VmS8azUHdKzrCsyZZDc9zbeLiLnK69WrWjNIal6YxMQTYw2nd4unNAe/Ab+8uj3XyVIs9mu3W66SmwkAMI3PIuV3bMUEmzGlfc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
