travis:
  secure:
    BINSTAR_TOKEN: ZCWLRgG8WR6yG3bOMdhHc140KsYXWKFA/oVZutZSaevIF7GQO4WK1Bkmljz5t4sf80bdQIBo2D7jIkoOo5mmve+vlFplVeKuxavqYh1fRUkJlYayRxZ88w5aijwwvuP6MOTQOO40/FNM1vTaG55MNLd69W4wvNOQ43UdLcUEY+gMqa/7KwNxKxUkGdzFRmL39NKjCxtzLct4QE6eRHW430WCknnv8Umxcgu+JahJ4bROtzxqH2RfMEuwTDq6hB15bhMaubPVhmsSUf0QOpqJ1knZQl5pMw0sk9ADkxWzvNxu+lzhAfMikk/m+4/5TAWRz9JUwYZkfVDecRJv+hoAJdezM5fUmKHi1Byg9D0Vp74iH+irEJoNFNZNP/4fIGyadzQyNMQiDE0mN8RvzrNo6+KTHjXB7b3WpaAx9LB10+j/KCY9LBkA/mFzmX2C1xsiW8klb8SBnPGBZkrbjeupKq3l/qS7SWNaG6y+VP1sS4LWp46UaaVAkcHIDdl/tSANu7BLadAe+yYqt3g9otB6fjpqoUaWo96F53ePMwssEHH9lXhcrxX8JdcbUxCt8hGCKi4JS7cxEtqdzMNeU3zy4/kB1ijsICqIDpJNYhdn6D6d53GxxRMqFgiMMGKgabiuFOdPl/r62C1CLw03UTzMZtw4D6MBHbYLBXHpp8P9P40=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
