travis:
  secure:
    BINSTAR_TOKEN: OXno239omjjPuM1ywOQonU80MkfnGCB9rn1NC9zdOhNgmW8a5VW5RbzDrH65gNCYKgVD4LGgwr79ASdzWcQlM1Lbl/hAjb6h0kB26Cxb5F/xn3JR8CNcukbvOyyzWGdkexjioegjTuqSKmNDaFa8OmR7m427lAU9tPAd8nNRklTkuk+xq3zPrAzgIu6B8zs8c+Dxxo5QWJk/WaLYgzNh0JE1Oo2OpmQYkT7TPPji/nfPunWdwhLzacLq57pOiAob9Y7ZRpBd90AzNT7c0HlIMBOw4lVaudysxdKKVa8ON3h4gYmcttRfvB5NHeXVrQNXUwsAVc86GjkgYADTB/5LeRWTRe9rddePdjauW9d0X+CFgJWrsq9RZoQ65hXP9r65CSIYGQbJifNuMi1IeWoxaLYSD3TRv7nK9VzgcIwWCVkWk7OkijHBLYrOtlPPAKP6FPFQXpqLTg6Yq6mAk+O/1fVL9yIXFSsMbx+tZjQLg4cE7cai0BhQ3RW4ty8CwYi3A3MuXYuVhzApxkGpLRdYld7BpIjIkDWYsSs9zKKsjHzg8w/ZApkzXxrcJvIKkrRJapjfmdU0M+U6ExsMc6IpokoURGpi1SM+OuGk5DXWTtSXWVaV3TqaYlhqhtvUhgsdGDRTOstCHCso2yUtEm40owYQd5DdGy5LHixo6aExbNk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
