travis:
  secure:
    BINSTAR_TOKEN: hmpHdGO+EB3S7QH/hvoP8tr6MlhgWi57ihwv60mv97LlX3seJMLvlKZkoVqh8xVdtZ/mfBckMQPfbQidPUGVUSPkW01psTZVciWrmWzAii5omOiMx/WmwURhUOd0lJAc2bZejfUGljHfwJY+Natk0RzBjJtckUpUredB1XttgLxarbijFHBNNKyGmUyMADBPlqPuKKJi+/X/9KnYAmJXgdRXM4OntfNr2GooSdOlwU3Vtjy2UXiYaBepagb7B5MRMbOngmn0A1yS6wjl7sPtImvQ7Ifd/XqHQuNKrjdeVd8HtYTWg9NSrwpUPBtyndHTf2MHOmaMPVj8ioYUrW/KMAaJkOkQgpbKe/FbQ+FJvhPT0nx9qehoqgAXe8hJqT/lIy0y+dmFumU9/xrunypA4wjnT21j2zepfoXkpzJWiWiL1BXOPfvRE+nDBDyWiAMVvDwuk1Jopz6Z+//gVVnNpApbcRgVqTX6Kgt5uCZPqYtLAZw7Jvg5lc88rhr2Goif9iAmvTvP5eV9OJ275DJkQBalP/5BCgVrZME/aLROQv7jJ6yGTCaABlUNV22qapOM1p1NwPiinptur7co7gDw3qADhm2oMOYpJjy58FDKAi6UA4Hl8YfWMHB0mLo5IdkdpFBViyQ3tDgnjpZxvIhnUUkRrdb0F6Sv5wJ9UsFAysU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
