travis:
  secure:
    BINSTAR_TOKEN: hG6IW+9F0pw9ECDqe0uxghOIHXW4IBlo41hk9m11RvcFjwtB/fAyx9gr4H27q2QzuGmzoS8+pi4LqXTTDTdm3A0cCBAyUQ3wUbYsAugwlZFlHyNTb7cx9+qFLnUOdvJbpNTKcMpoQW7F57yOjLATxdmW4Q+195bqifxYiLnthNeyWX/eVd7O2E07LDvEBGbpLSXnAWVkwiwjCRDn1CLYD7rNcrGZyyl5cQqG3NW78c7jqkG7jO3A0QWzJcV90eEtq5g5DHjbN8ldqOx2AhYmVZlOO16fxN4CkRgGN3Ced28r7aQctzOzJBt1JBumLyq5bwbmJf+k6MO1U6a9e7NmY4SqqcXIAlJh2V5VFNYsUhKBKh1BvxXO4HWaWkgtrAs4oUR6Qp76Y4/9b3eNlApsxW8hy/miY6+sDyekdi1jrSSgsFI9aICprKHCpTl1Uu8Tois6y3erXwstAC8I3cWjhVIWxNXXf0RuU+FttDT7zk6PlJoWuXU9y5dk6TqwCreViXNHmJFgoYu0HhllOE0FTjcegcwb7Jy34l/0mkYOeLxCMTKHnTSIBGWmCABDJlhraUpQ1pg5kkJ0XmZgEtODTGLglUkwKUWXEGtxhloNbn8bqfm4fNnGWiQ8H1FIfT2mlKKSJhyoJCNsln2gIbzB2Z+ciRNAOjqaQYCK14Ww2qI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
