travis:
  secure:
    BINSTAR_TOKEN: W2P+47WjwLpXK5wBS0quR0oR7APh3LVXEUdhbcpoiAMPczX/X3ER6AAs7prqNXaHYUH4lLF+XBa/42d3x6npejdZyvbOP3dBUtFMWcFohXEpYQJusXmmcVOI+jaHJJbd5FJcCGP7pt/SKrGQot16SWpSbD9tamCAhW3q5Oyi7ZGUjLzRZxoO3hXO9UTpRhqMcEUEmilHMDXbOvK7GZQCBR36Zr1yxvjs/KdNtbFVMFk7ZFvjwgBOTJ+df0uu5SwNlgLWUhg3Ip5CIc3EYw5PdbZy+LC84YjzQoesXCMcxMkPbUoSUMavOnv4PYi1h+YWunfVQVxvSWD14dcy+B9xkk8RX3S9TNNmk4ow52lT2d/7j33Mc+YhTZ2FzGXGLIpqR2djK64S3gr+yjPQt3v0agIyLmvgi2ppcoRU0FIRDwusm328cIdoN14ZSKuxjeQIzbe8F7qi7WDaz/zirwjt54q5fU1+CVjRPiEHFwH7IWPY4LDpIa3d5988LsycIAIS2++2STMUz4RZW/sknAh5RcaJLMVEknRygEn+GS8fiu2SUtCj+SHgdIa/WTD4s5htTakTO8aMhL+g2UBesekxrINNLXwDcli5zrsYTncjXCB0FJtktdMj8Ll3UmUXsaQzd1B9funLNRj1K1/nGRZ9HIcOw71tAlCrbBW3tnMe9BA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
