travis:
  secure:
    BINSTAR_TOKEN: hIFA6t/h/VXwc9AAsWOeNaLW7JK39oqFIvKPayCd5UWSCtiINNpNBNY7fzljPclZRrzw3reJ1ebtGsMTSqovXBHwiYX1VpD8t5V/wsBFJ/qA1+/tSVfAGlPOmrkLbxWNdO53Z2iOCYJ1jGmzy8XZrjV5f/V+Y38tUeoBDuH2MvFdNynDc/lECnVhul8VNTL/ZYuYwpYhavkvo0UrglXayZ9ObRpS+1fWi+PVfGtSRNOUd4MmTgFZRwEdhmw0C8GWZpnV8MHnzKds/aOBLILYliZtAxaVxB1jQTcaq3mNloSTxIC5pwsa4rH2IlxfNfzpVJLrR/N7disLaLswzwg9EgkIYI3Vm47VN+9XwtDlyXwI/vtYyeJVoMaJNKEEzfrtoGE44lO/XWVWBSxYtN+U02fL0KvUEN6n7tL3F4j+vv04xyQHtlVZqlvXSHZ2Kqg+rh9Xqv7RKBtHici0nZR5gzEHMmmuNgiSnXBpcWxnyQIzJ5Two0X2+PdiEB58GSUxtlWHcwMoxI/UjC1W9oDjPFnwCvPOvwx6NaoGaFWpFm0A0n3lifObs3ZQuwAw3igNkSTkvSQUpcpErVVXXjtPNqskbFi964x1zPxFASewQyl6ly2fNy3fOzev/P1X+pbxhQyNEYAZNTFjsmTREn8+Yrab6sxKm91AzQdaM//T69Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
